//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult, TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
/**
 * User model
 */
export type User = $ModelResult<$Schema, "User">;
/**
 * Post model
 */
export type Post = $ModelResult<$Schema, "Post">;
/**
 * Profile type definition
 */
export type Profile = $TypeDefResult<$Schema, "Profile">;
/**
 * User role
 */
export const Role = $schema.enums.Role.values;
/**
 * User role
 */
export type Role = (typeof Role)[keyof typeof Role];
